import { BASE_TOKENS } from "./baseTokens";

const Colors = {
  COMMON: {
    SURFACE: {
      BASE: BASE_TOKENS.COLORS.NEUTRAL["00"],
    },
    MAIN: {
      BASE: BASE_TOKENS.COLORS.NEUTRAL["100"],
    },
  },
  BRAND: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.BRAND["10"],
      BASE: BASE_TOKENS.COLORS.BRAND["20"],
      WEAK: BASE_TOKENS.COLORS.BRAND["30"],
      WEAKER: BASE_TOKENS.COLORS.BRAND["40"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.BRAND["90"],
      STRONG: BASE_TOKENS.COLORS.BRAND["80"],
      BASE: BASE_TOKENS.COLORS.BRAND["70"],
      WEAK: BASE_TOKENS.COLORS.BRAND["60"],
      WEAKER: BASE_TOKENS.COLORS.BRAND["50"],
    },
  },
  NEUTRAL: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.NEUTRAL["40"],
      BASE: BASE_TOKENS.COLORS.NEUTRAL["30"],
      WEAK: BASE_TOKENS.COLORS.NEUTRAL["20"],
      WEAKER: BASE_TOKENS.COLORS.NEUTRAL["10"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.NEUTRAL["90"],
      STRONG: BASE_TOKENS.COLORS.NEUTRAL["80"],
      BASE: BASE_TOKENS.COLORS.NEUTRAL["70"],
      WEAK: BASE_TOKENS.COLORS.NEUTRAL["60"],
      WEAKER: BASE_TOKENS.COLORS.NEUTRAL["50"],
    },
  },
  POSITIVE: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.POSITIVE["40"],
      BASE: BASE_TOKENS.COLORS.POSITIVE["30"],
      WEAK: BASE_TOKENS.COLORS.POSITIVE["20"],
      WEAKER: BASE_TOKENS.COLORS.POSITIVE["10"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.POSITIVE["90"],
      STRONG: BASE_TOKENS.COLORS.POSITIVE["80"],
      BASE: BASE_TOKENS.COLORS.POSITIVE["70"],
      WEAK: BASE_TOKENS.COLORS.POSITIVE["60"],
      WEAKER: BASE_TOKENS.COLORS.POSITIVE["50"],
    },
  },
  WARNING: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.WARNING["40"],
      BASE: BASE_TOKENS.COLORS.WARNING["30"],
      WEAK: BASE_TOKENS.COLORS.WARNING["20"],
      WEAKER: BASE_TOKENS.COLORS.WARNING["10"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.WARNING["90"],
      STRONG: BASE_TOKENS.COLORS.WARNING["80"],
      BASE: BASE_TOKENS.COLORS.WARNING["70"],
      WEAK: BASE_TOKENS.COLORS.WARNING["60"],
      WEAKER: BASE_TOKENS.COLORS.WARNING["50"],
    },
  },
  NEGATIVE: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.NEGATIVE["40"],
      BASE: BASE_TOKENS.COLORS.NEGATIVE["30"],
      WEAK: BASE_TOKENS.COLORS.NEGATIVE["20"],
      WEAKER: BASE_TOKENS.COLORS.NEGATIVE["10"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.NEGATIVE["90"],
      STRONG: BASE_TOKENS.COLORS.NEGATIVE["80"],
      BASE: BASE_TOKENS.COLORS.NEGATIVE["70"],
      WEAK: BASE_TOKENS.COLORS.NEGATIVE["60"],
      WEAKER: BASE_TOKENS.COLORS.NEGATIVE["50"],
    },
  },
  ACCENT: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.ACCENT["40"],
      BASE: BASE_TOKENS.COLORS.ACCENT["30"],
      WEAK: BASE_TOKENS.COLORS.ACCENT["20"],
      WEAKER: BASE_TOKENS.COLORS.ACCENT["10"],
    },
    MAIN: {
      STRONGER: BASE_TOKENS.COLORS.ACCENT["90"],
      STRONG: BASE_TOKENS.COLORS.ACCENT["80"],
      BASE: BASE_TOKENS.COLORS.ACCENT["70"],
      WEAK: BASE_TOKENS.COLORS.ACCENT["60"],
      WEAKER: BASE_TOKENS.COLORS.ACCENT["50"],
    },
  },
} as const;

export type ColorCategoryName = keyof typeof Colors;
export type ColorForce<Category extends ColorCategoryName> =
  keyof (typeof Colors)[Category]["MAIN"];

export const TOKEN = {
  COLOR: Colors,
  FONT: {
    ...BASE_TOKENS.FONTS,
  },
  SIZE: {
    GAP: {
      XXXL: BASE_TOKENS.SPACES.XXXL,
      XXL: BASE_TOKENS.SPACES.XXL,
      XL: BASE_TOKENS.SPACES.XXL,
      L: BASE_TOKENS.SPACES.XL,
      M: BASE_TOKENS.SPACES.L,
      S: BASE_TOKENS.SPACES.M,
      XS: BASE_TOKENS.SPACES.S,
      XXS: BASE_TOKENS.SPACES.XS,
    },
    PADDING: {
      VERTICAL: {
        L: BASE_TOKENS.SPACES.M,
        M: BASE_TOKENS.SPACES.S,
        S: BASE_TOKENS.SPACES.XS,
      },
      HORIZONTAL: {
        L: BASE_TOKENS.SPACES.L,
        M: BASE_TOKENS.SPACES.M,
        S: BASE_TOKENS.SPACES.S,
      },
    },
  },
  RADIUS: {
    ROUND: "9999px",
    INTERACTIVE: BASE_TOKENS.SPACES.S,
    BASE: BASE_TOKENS.SPACES.XS,
  },
  SHADOW: {
    OUTSET: {
      5: `0px 0px 24px rgba(0, 0, 0, 0.05), 0px 16px 24px rgba(0, 0, 0, 0.25)`,
      4: `0px 0px 16px rgba(0, 0, 0, 0.05), 0px 8px 16px rgba(0, 0, 0, 0.25)`,
      3: `0px 0px 16px rgba(0, 0, 0, 0.05), 0px 4px 8px rgba(0, 0, 0, 0.25)`,
      2: `0px 0px 8px rgba(0, 0, 0, 0.05), 0px 2px 4px rgba(0, 0, 0, 0.25)`,
      1: `0px 0px 4px rgba(0, 0, 0, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.25)`,
    },
    INPUT: `inset 0px 0px 8px rgba(0, 0, 0, 0.05), inset 0px 2px 4px rgba(0, 0, 0, 0.25)`,
  },
  SEPARATOR: {
    BASE: `1px solid ${Colors.NEUTRAL.SURFACE.STRONG}`,
  },
} as const;
