import { BASE_TOKENS } from "./baseTokens";

export const TOKEN = {
  COMMON: {
    SURFACE: BASE_TOKENS.COLORS.NEUTRAL["00"],
    MAIN: BASE_TOKENS.COLORS.NEUTRAL["100"],
  },
  ACTION: {
    SURFACE: {
      STRONG: BASE_TOKENS.COLORS.PRIMARY["20"],
      BASE: BASE_TOKENS.COLORS.PRIMARY["20"],
      WEAK: BASE_TOKENS.COLORS.PRIMARY["20"],
    },
    MAIN: {
      STRONG: BASE_TOKENS.COLORS.PRIMARY["90"],
      BASE: BASE_TOKENS.COLORS.PRIMARY["80"],
      WEAK: BASE_TOKENS.COLORS.PRIMARY["70"],
    },
  },
} as const;
